# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  # Collector metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

  githubactions:
    endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:GHA_PORT}
    path: /events
    cors:
      allowed_origins: ["*"]
      allowed_headers: ["*"]

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: fluentbit:${env:OTEL_COLLECTOR_PORT_HTTP}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
